# Generated by Django 4.2.7 on 2025-06-24 13:28

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
